// Generated by gencpp from file damiao_msgs/DmCommand.msg
// DO NOT EDIT!


#ifndef DAMIAO_MSGS_MESSAGE_DMCOMMAND_H
#define DAMIAO_MSGS_MESSAGE_DMCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace damiao_msgs
{
template <class ContainerAllocator>
struct DmCommand_
{
  typedef DmCommand_<ContainerAllocator> Type;

  DmCommand_()
    : joint_names()
    , pos()
    , vel()
    , kp()
    , kd()
    , tau()  {
    }
  DmCommand_(const ContainerAllocator& _alloc)
    : joint_names(_alloc)
    , pos(_alloc)
    , vel(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , tau(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pos_type;
  _pos_type pos;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _vel_type;
  _vel_type vel;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kp_type;
  _kp_type kp;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _kd_type;
  _kd_type kd;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _tau_type;
  _tau_type tau;





  typedef boost::shared_ptr< ::damiao_msgs::DmCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::damiao_msgs::DmCommand_<ContainerAllocator> const> ConstPtr;

}; // struct DmCommand_

typedef ::damiao_msgs::DmCommand_<std::allocator<void> > DmCommand;

typedef boost::shared_ptr< ::damiao_msgs::DmCommand > DmCommandPtr;
typedef boost::shared_ptr< ::damiao_msgs::DmCommand const> DmCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::damiao_msgs::DmCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::damiao_msgs::DmCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::damiao_msgs::DmCommand_<ContainerAllocator1> & lhs, const ::damiao_msgs::DmCommand_<ContainerAllocator2> & rhs)
{
  return lhs.joint_names == rhs.joint_names &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.tau == rhs.tau;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::damiao_msgs::DmCommand_<ContainerAllocator1> & lhs, const ::damiao_msgs::DmCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace damiao_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::damiao_msgs::DmCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::damiao_msgs::DmCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::damiao_msgs::DmCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::damiao_msgs::DmCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::damiao_msgs::DmCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::damiao_msgs::DmCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::damiao_msgs::DmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2b620aeb6044700d6c7585f10679d8c";
  }

  static const char* value(const ::damiao_msgs::DmCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2b620aeb6044700ULL;
  static const uint64_t static_value2 = 0xd6c7585f10679d8cULL;
};

template<class ContainerAllocator>
struct DataType< ::damiao_msgs::DmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "damiao_msgs/DmCommand";
  }

  static const char* value(const ::damiao_msgs::DmCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::damiao_msgs::DmCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] joint_names\n"
"float64[] pos\n"
"float64[] vel\n"
"float64[] kp\n"
"float64[] kd\n"
"float64[] tau\n"
;
  }

  static const char* value(const ::damiao_msgs::DmCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::damiao_msgs::DmCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_names);
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DmCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::damiao_msgs::DmCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::damiao_msgs::DmCommand_<ContainerAllocator>& v)
  {
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.kd[i]);
    }
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DAMIAO_MSGS_MESSAGE_DMCOMMAND_H
